version: "3.9"

services:
  app:
    image: ghcr.io/folkloria-team/dashboard-app:latest
    container_name: nextjs-app
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: "0.0.0.0"
    restart: unless-stopped
